INSERT INTO Teacher (name, surname, nickname, email,  password ) VALUES ('Tomas','Mann','TheBestTeacher', 'olikdiz@mail.ru', '000');
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname) VALUES (true, 'elton@john', 'aaa', 'Elton', 'Rocketman', '111', 90, 'John');
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname) VALUES (true, 'john@john', 'bbb', 'John', 'Dirty', '111', 100, 'Johnovich');
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname) VALUES (true, 'leonardo@oscar', 'bbb', 'Leonardo', 'Leo', '111', 120, 'DiCaprio');
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname) VALUES (true, 'elon@cosmos', 'bbb', 'Elon', 'Mars', '111', 100, 'Musk');
INSERT INTO Slot (isBooked, isOnceFree, date, time, dayOfWeek, regularStudent_id, teacher_id) VALUES (true, true, '2020-11-19', '20:10:00', 0,  1,1);
INSERT INTO Slot (isBooked, isOnceFree, date, time, dayOfWeek, regularStudent_id, teacher_id) VALUES (true, false, null, '19:10:00', 1, 1, 1);
INSERT INTO Slot (isBooked, isOnceFree, date, time,dayOfWeek,  regularStudent_id, teacher_id) VALUES (true, false, null, '15:10:00', 3, 2, 1);
INSERT INTO Slot (isBooked, isOnceFree, date, time, dayOfWeek, regularStudent_id, teacher_id) VALUES (true, false, null, '14:00:00', 3, 3, 1);
INSERT INTO Slot (isBooked, isOnceFree, date, time, dayOfWeek, regularStudent_id, teacher_id) VALUES (true, false, null, '20:00:00', 3, 4, 1);
INSERT INTO Slot (isBooked, isOnceFree, date, time,dayOfWeek,  regularStudent_id, teacher_id) VALUES (false, false, null, '10:00:00', 3, null, 1);
INSERT INTO Slot (isBooked, isOnceFree, date, time, dayOfWeek, regularStudent_id, teacher_id) VALUES (false, false, null, '11:00:00', 1, null, 1);
INSERT INTO Slot (isBooked, isOnceFree, date, time,dayOfWeek,  regularStudent_id, teacher_id) VALUES (false, false, null, '13:00:00', 0, null, 1);
INSERT INTO Slot (date, dayOfWeek, isBooked, isOnceFree, time, regularStudent_id, teacher_id) VALUES (null, 6, true, false, '20:59:00', 3, 1);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 1);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 2);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 3);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 4);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 46, 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 47, 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 48, 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 49, 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 50, 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 51, 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 52, 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id) VALUES ('F', 'F', 53, 2020, 1);