INSERT INTO Teacher (name, surname, nickname, email,  password ) VALUES ('Winni','Pooh','TheBestTeacher', 'olikdiz@mail.ru', '000');
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname, overpayment) VALUES (true, 'elton@john', 'aaa', 'Elton', 'Rocketman', '111', 90, 'John',0);
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname, overpayment) VALUES (true, 'john@john', 'bbb', 'John', 'Dirty', '111', 100, 'Johnovich',0);
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname, overpayment) VALUES (true, 'leonardo@oscar', 'bbb', 'Leonardo', 'Leo', '111', 120, 'DiCaprio',0);
INSERT INTO Student (active, email, login, name, nickname, password, priceForOneLesson, surname, overpayment) VALUES (true, 'elon@cosmos', 'bbb', 'Elon', 'Mars', '111', 100, 'Musk',0);
INSERT INTO Slot (booked, time, dayOfWeek, regularStudent_id, teacher_id, archived) VALUES (true, '11:10:00',  0,  1,1, false);
INSERT INTO Slot (booked, time, dayOfWeek, regularStudent_id, teacher_id, archived) VALUES (true, '19:10:00', 1, 1, 1, false);
INSERT INTO Slot (booked, time,dayOfWeek,  regularStudent_id, teacher_id, archived) VALUES (true, '15:10:00', 3, 2, 1, false);
INSERT INTO Slot (booked, time, dayOfWeek, regularStudent_id, teacher_id, archived) VALUES (true, '14:00:00', 3, 3, 1, false);
INSERT INTO Slot (booked, time, dayOfWeek, regularStudent_id, teacher_id, archived) VALUES (true, '20:00:00', 3, 4, 1, false);
INSERT INTO Slot (booked, time,dayOfWeek,  regularStudent_id, teacher_id, archived) VALUES (false, '10:00:00', 3, null, 1, false);
INSERT INTO Slot (booked, time, dayOfWeek, regularStudent_id, teacher_id, archived) VALUES (false, '11:00:00', 1, null, 1, false);
INSERT INTO Slot (booked, time,dayOfWeek,  regularStudent_id, teacher_id, archived) VALUES (false, '13:00:00', 0, null, 1, false);
INSERT INTO Slot (date, dayOfWeek, isBooked, isOnceFree, time, regularStudent_id, teacher_id) VALUES (null, 6, true, false, '20:59:00', 3, 1);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 1);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 2);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 3);
INSERT INTO dinosauruski.teachers_students (teacher_id, student_id) VALUES (1, 4);
INSERT INTO dinosauruski.YearForTeacher (isArchived, isGenerated, year, teacher_id) VALUES ('F', 'T', 2020, 1);
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 1, 2020, 1, '2020-12-30');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 2, 2020, 1,'2020-01-06');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 3, 2020, 1, '2020-01-13');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 4, 2020, 1, '2020-01-20');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 5, 2020, 1, '2020-01-27');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 6, 2020, 1, '2020-02-03');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 7, 2020, 1, '2020-02-10');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 8, 2020, 1, '2020-02-17');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 9, 2020, 1, '2020-02-24');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 10, 2020, 1, '2020-03-02');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 11, 2020, 1, '2020-03-09');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 12, 2020, 1, '2020-03-16');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 13, 2020, 1, '2020-03-23');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 14, 2020, 1, '2020-03-30');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 15, 2020, 1, '2020-04-6');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 16, 2020, 1, '2020-04-13');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 17, 2020, 1, '2020-04-20');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 18, 2020, 1, '2020-04-27');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 19, 2020, 1, '2020-05-04');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 20, 2020, 1, '2020-05-11');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 21, 2020, 1, '2020-05-18');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 22, 2020, 1, '2020-05-25');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 23, 2020, 1, '2020-06-01');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 24, 2020, 1, '2020-06-08');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 25, 2020, 1, '2020-06-15');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 26, 2020, 1, '2020-06-22');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 27, 2020, 1, '2020-06-29');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 28, 2020, 1, '2020-07-06');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 29, 2020, 1, '2020-07-13');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 30, 2020, 1, '2020-07-20');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 31, 2020, 1, '2020-07-27');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 32, 2020, 1, '2020-08-03');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 33, 2020, 1, '2020-08-10');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 34, 2020, 1, '2020-08-17');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 35, 2020, 1, '2020-08-24');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 36, 2020, 1, '2020-08-31');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 37, 2020, 1, '2020-09-07');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 38, 2020, 1, '2020-09-14');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 39, 2020, 1, '2020-09-21');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 40, 2020, 1, '2020-09-28');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 41, 2020, 1, '2020-10-05');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 42, 2020, 1, '2020-10-12');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 43, 2020, 1, '2020-10-19');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 44, 2020, 1, '2020-10-28');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 45, 2020, 1, '2020-11-02');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 46, 2020, 1, '2020-11-09');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 47, 2020, 1, '2020-11-16');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 48, 2020, 1, '2020-11-23');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 49, 2020, 1, '2020-11-30');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 50, 2020, 1, '2020-12-07');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 51, 2020, 1, '2020-12-14');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 52, 2020, 1, '2020-12-28');
INSERT INTO dinosauruski.Week (isArchived, isGenerated, numberOfWeek, year, teacher_id, mondayDate) VALUES ('F', 'F', 53, 2020, 1, '2020-12-30');